{% set version = '2.5-4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-vegan
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/vegan_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/vegan/vegan_{{ version }}.tar.gz
  sha256: 5116a440111fca49b5f95cfe888b180ff29a112e6301d5e2ac5cae0e628493e0

build:
  merge_build_host: True  # [win]
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-mass
    - r-cluster
    - r-lattice
    - r-mgcv
    - r-permute >=0.9_0

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mass
    - r-cluster
    - r-lattice
    - r-mgcv
    - r-permute >=0.9_0

test:
  commands:
    - $R -e "library('vegan')"  # [not win]
    - "\"%R%\" -e \"library('vegan')\""  # [win]

about:
  home: https://cran.r-project.org, https://github.com/vegandevs/vegan
  license: GPL-2
  summary: Ordination methods, diversity analysis and other functions for community and vegetation
    ecologists.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
