appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: huTfubJAZSq8leuzcNJ9OLmJyp77QjaziNo4C8JPDjHieSHragjvVd5/UgywfCZUii1JJ/QUD7LfohHbtjNU52TTFFwzH5yIv2RaZihf/qKnLaE9oSdRKX3Oro71qnTfswdxKsT4l8XwRTIMn/wKzvYyrc8ex5AbB8sMR/0DANuF+fxpe0JHLDmpbHvYOV/9v/kT3NOaVRrmN7EPr030x0Y+oRrpnsg8PezBH7AD1u7nn0+Co3ie19U8RknIv6Q3iZ0aQllCVAgliLzKOs/rbKfZ3YSUAu4J/2d+s+LMNke3iKwxcM4O0DX9g6kSrdgZ8ZxNJwyoEPg+0WDPeHEZrR5jg8CFcKVrB+AvP1043EP0kYC3yelZPA3dSmuEOkTPai4wHm3WcxA/jWJCg8JLS7J7XCWsT1ZMX8Yq499ToujvUorDUBW26pIOfB7uEGwSosznULtVLKZiVkGEe+rVylor8ScW1izf7fe//+ik7b1dWEv/oD3ARQZi8r9aNwN4aHJxwUIFos8GVAvApDHceUsuW0N9cAJxjo1qXUPdyK/Kx2Kv/x4+KsHBrK2S79OkdCkcbkP7tvLJacbaInQ68j/IE80j2JyKYGsh8v4ptHo8pXXNcCEntS8sFjD2SouR+6Oub1eVe1MRIwvvgn+tzUTZn5UEx1BNYpK2UJ776Cc=
